---
# tasks file for absis-installer
- name: Install files using apt-get
  apt:
    name={{ item }}
    state=latest
  become: yes
  with_items:
    - samba
    - mosh
    - ddclient
    - mysql-client

- name: Install docker-py
  pip:
    name={{item}}
    state=latest
  become: yes
  with_items:
    - docker-py

- name: Add user to docker group
  user: name=tstapler groups=docker append=yes
  become: yes

- name: Set Data Directory
  set_fact:
    stapler_data_dir: "/home/tstapler/The_Archive"
  tags:
    - always

- name: Find users uid
  shell: "id | awk 'match($0, /uid=([0-9]+)/) { print substr( $1, RSTART, RLENGTH)}' | sed 's/uid=//g'"
  register: uid
  tags:
    - always

- name: Find users gid
  shell: "id | awk 'match($0, /gid=([0-9]+)/) { print substr( $0, RSTART, RLENGTH)}' | sed 's/gid=//g'"
  register: gid
  tags:
    - always

- name: Set uid and gid
  set_fact:
    docker_puid: "{{uid.stdout}}"
    docker_pgid: "{{gid.stdout}}"
  tags:
    - always

- debug: msg="docker puid - {{docker_puid}}, docker guid - {{docker_pgid}}"
  tags:
    - always

- name: Link ddclient systemd timer
  file:
    src: "{{playbook_dir}}/files/{{item}}"
    dest: "/etc/systemd/system/{{item}}"
    state: link
  with_items:
    - "staplerstation-ddclient.service"
  become: yes

