---
# tasks file for absis-installer
- name: Install files using apt-get
  apt:
    name={{ item }}
    state=present
  become: yes
  with_items:
    - samba
    - mosh

- name: Install docker-py
  pip:
    name={{item}}
    state=present
  become: yes
  with_items:
    - docker-py
