---
- pause: 
    seconds: 10
- name: Add Pydio database
  mysql_db:
    name: pydio
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
    
# tasks file for pydio
- name: Create Pydio Container
  docker:
    name: pydio
    image: linuxserver/pydio
    state: started
    restart_policy: always
    links: "mariadb:db"
    ports:
      - "4000:443"
      - "4001:80"
    env:
      RANCHER_NETWORK=true,
      VERSION=latest,
      PUID={{ docker_puid }},
      GUID={{ docker_pgid }}
    volumes: "{{ pydio_volumes }}"
