---

dependencies: []

galaxy_info:
  author: 'Tyler Stapler'
  description: 'mariadb described in 1 sentence...'
  company: ''
  license: 'MIT'
  min_ansible_version: '1.7.1'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  categories: []
