---
pudio_required_host_dirs:
  - "{{ stapler_data_dir }}/Pydio"

# vars file for pydio
pydio_volumes:
  - "{{ stapler_data_dir }}/Pydio:/config"
  - "{{ stapler_data_dir }}/The File Database:/data"
  - "/etc/localtime:/etc/localtime:ro"
