---
# tasks file for plex
- name: Create Plex Container
  docker: 
    name: plex
    image: linuxserver/plex
    state: reloaded
    restart_policy: always
    net: host
    env:
      RANCHER_NETWORK=true,
      VERSION=latest,
      PUID={{ plex_puid }},
      GUID={{ plex_guid }}
    volumes: "{{ plex_volumes }}"
