---
# tasks file for plex
- name: Create Plex Container
  docker:
    name: plex
    image: linuxserver/plex
    state: reloaded
    restart_policy: always
    env:
      RANCHER_NETWORK=true,
      VERSION=latest,
      PUID={{ docker_puid }},
      PGID={{ docker_pgid }}
    volumes: "{{ plex_volumes }}"
